/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-13 11:16:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://it21209352.github.io/css/register.css\">\r\n");
      out.write("<title>register</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"split-screen\">\r\n");
      out.write("		<div class=\"split-left\">\r\n");
      out.write("			<section class=\"cpy\">\r\n");
      out.write("				<h1>\r\n");
      out.write("					Travel far enough, <br>You meet Yourself\r\n");
      out.write("				</h1>\r\n");
      out.write("				<p>Visit Sri Lanka</p>\r\n");
      out.write("			</section>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"split-right\">\r\n");
      out.write("			<form action=\"RegisterServlet\" method=\"post\">\r\n");
      out.write("				<section class=\"cpy\">\r\n");
      out.write("					<h2>SIGNUP</h2>\r\n");
      out.write("					<div class=\"sign-in\">\r\n");
      out.write("						<p>\r\n");
      out.write("							Already have an Account ? <a href=\"Login.jsp\"><Strong>Sign\r\n");
      out.write("									In</Strong></a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"con-name\">\r\n");
      out.write("					<label for=\"name\">Name</label> <input id=\"nme\" type=\"text\"\r\n");
      out.write("						name=\"Name\" placeholder=\"Enter your Name\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"con-email\">\r\n");
      out.write("					<label for=\"email\">Email</label> <input id=\"emil\" type=\"email\"\r\n");
      out.write("						name=\"Email\" placeholder=\"Enter your Email\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"con-tel\">\r\n");
      out.write("					<label for=\"telphone\">Telephone</label> <input id=\"TP\" type=\"text\"\r\n");
      out.write("						name=\"Mobile\" placeholder=\"Enter your mobile number\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"con-password\">\r\n");
      out.write("					<label for=\"password\"> Create Password</label> <input id=\"pwd\"\r\n");
      out.write("						type=\"password\" name=\"psw\" placeholder=\"Enter Password\"\r\n");
      out.write("						pattern=\"(?-.*\\d)(?-.*[a-z])(?-.*[A-Z]).{8,}\" required> <i\r\n");
      out.write("						class=\"far fa-eye-slash\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"con-password\">\r\n");
      out.write("					<label for=\"password\"> Re-Enter Password</label> <input id=\"rpwd\"\r\n");
      out.write("						type=\"password\" name=\"psw\" placeholder=\"Enter Password\"\r\n");
      out.write("						pattern=\"(?-.*\\d)(?-.*[a-z])(?-.*[A-Z]).{8,}\" required onkeyup='check();'> <i\r\n");
      out.write("						class=\"far fa-eye-slash\"></i>\r\n");
      out.write("						  <span id = \"message2\" style=\"color:red\"> </span>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("				<section class=\"copy legal\">\r\n");
      out.write("					<p>\r\n");
      out.write("						<span class=\"small\">Agree to accept our <a href=\"#\">Privacy\r\n");
      out.write("								Policy</a> &amp; <a href=\"#\">Terms and Conditions</a></span>\r\n");
      out.write("					</p>\r\n");
      out.write("				</section>\r\n");
      out.write("				<br>\r\n");
      out.write("\r\n");
      out.write("				<button class=\"log-btn\" type=\"submit\"  id=\"submit\" disabled>SIGN UP</button>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<script>\r\n");
      out.write("		function check(){\r\n");
      out.write("			if(document.getElementById(\"pwd\").value !=\r\n");
      out.write("			document.getElementById(\"rpwd\").value)\r\n");
      out.write("			{\r\n");
      out.write("				      document.getElementById(\"message2\").innerHTML = \"**Passwords are not same\";\r\n");
      out.write("				      return false;\r\n");
      out.write("				    }\r\n");
      out.write("				else{\r\n");
      out.write("					document.getElementById(\"message2\").innerHTML = \" \";\r\n");
      out.write("					document.getElementById(\"submit\").disabled=false;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
